# Generated by Django 3.2 on 2025-03-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название букета:')),
                ('description', models.TextField(blank=True, verbose_name='Описание и состав букета:')),
                ('price', models.IntegerField(verbose_name='Цена в Р:')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='bouquets/', verbose_name='Фото букета:')),
                ('is_available', models.BooleanField(default=True, verbose_name='В продаже:')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления букета:')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения:')),
            ],
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название композиции:')),
                ('description', models.TextField(blank=True, verbose_name='Описание и состав композиции:')),
                ('price', models.IntegerField(verbose_name='Цена в Р:')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='compositions/', verbose_name='Фото композиции:')),
                ('is_available', models.BooleanField(default=True, verbose_name='В продаже:')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления композиции:')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения:')),
                ('event', models.CharField(choices=[('wedding', 'Для свадьбы'), ('march8', '8 марта'), ('teacher', 'Для учителя'), ('no_reason', 'Без повода')], default='no_reason', max_length=20, verbose_name='Мероприятие:')),
            ],
        ),
    ]
