# Generated by Django 5.1.7 on 2025-03-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название букета:')),
                ('description', models.TextField(blank=True, verbose_name='Описание и состав букета:')),
                ('price', models.IntegerField(verbose_name='Цена в Р:')),
                ('photo_url', models.URLField(blank=True, verbose_name='Фото букета:')),
                ('is_available', models.BooleanField(default=True, verbose_name='В продаже:')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления букета:')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения:')),
            ],
        ),
    ]
