# Generated by Django 4.2.20 on 2025-03-30 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название букета:')),
                ('description', models.TextField(blank=True, verbose_name='Описание и состав букета:')),
                ('price', models.IntegerField(verbose_name='Цена в Р:')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='bouquets/', verbose_name='Фото букета:')),
                ('is_available', models.BooleanField(default=True, verbose_name='В продаже:')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления букета:')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения:')),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя покупателя:')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Телефон:')),
                ('budget', models.IntegerField(blank=True, null=True, verbose_name='Ориентировочный бюджет:')),
                ('preferences', models.TextField(blank=True, verbose_name='Пожелания клиента:')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('completed', 'Завершена')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки:')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Имя покупателя:')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время поступления заказа:')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Телефон:')),
                ('delivery_address', models.TextField(verbose_name='Адрес доставки:')),
                ('order_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма заказа:')),
                ('postcard', models.TextField(default='', verbose_name='Текст открытки:')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Банковская карта'), ('online', 'Онлайн-оплата')], default='cash', max_length=10, verbose_name='Способ оплаты:')),
                ('status', models.CharField(choices=[('accepted', 'Принят'), ('processing', 'В работе'), ('on_delivery', 'На доставке'), ('completed', 'Завершён')], default='accepted', max_length=15, verbose_name='Статус заказа:')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bot.order')),
            ],
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название композиции:')),
                ('description', models.TextField(blank=True, verbose_name='Описание и состав композиции:')),
                ('price', models.IntegerField(verbose_name='Цена в Р:')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='compositions/', verbose_name='Фото композиции:')),
                ('is_available', models.BooleanField(default=True, verbose_name='В продаже:')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления композиции:')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения:')),
                ('event', models.CharField(choices=[('wedding', 'Для свадьбы'), ('march8', '8 марта'), ('teacher', 'Для учителя'), ('no_reason', 'Без повода')], default='no_reason', max_length=20, verbose_name='Мероприятие:')),
                ('bouquets', models.ManyToManyField(related_name='compositions', to='bot.bouquet')),
            ],
        ),
    ]
