# Generated by Django 5.1.7 on 2025-03-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bouquet',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='bouquet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='bouquets/', verbose_name='Фото букета:'),
        ),
    ]
