# Generated by Django 5.1.7 on 2025-03-27 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_composition'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Имя покупателя:')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время поступления заказа:')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Телефон:')),
                ('delivery_address', models.TextField(verbose_name='Адрес доставки:')),
                ('order_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма заказа:')),
                ('postcard', models.TextField(default='', verbose_name='Текст открытки:')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Банковская карта'), ('online', 'Онлайн-оплата')], default='cash', max_length=10, verbose_name='Способ оплаты:')),
                ('status', models.CharField(choices=[('accepted', 'Принят'), ('processing', 'В работе'), ('on_delivery', 'На доставке'), ('completed', 'Завершён')], default='accepted', max_length=15, verbose_name='Статус заказа:')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bot.order')),
            ],
        ),
    ]
