# Generated by Django 5.1.7 on 2025-03-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя покупателя:')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Телефон:')),
                ('budget', models.IntegerField(blank=True, null=True, verbose_name='Ориентировочный бюджет:')),
                ('preferences', models.TextField(blank=True, verbose_name='Пожелания клиента:')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('completed', 'Завершена')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки:')),
            ],
        ),
    ]
